import {StyleSheet} from 'react-native';
import {
  DARK_BLUE,
  DARK_GREY,
  LIGHT_GREEN,
  WHITE,
  GRAY_TEXT,
  WINDOW_HEIGHT,
  WINDOW_WIDTH,
} from '../../styles';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: DARK_BLUE,
  },
  topView: {
    paddingHorizontal: 20,
    position: 'absolute',
    zIndex: 0,
    width: '100%',
  },
  bottomView: {
    paddingHorizontal: 20,
    position: 'absolute',
    zIndex: 0,
    width: '100%',
    height: '30%',
    backgroundColor: 'white',
    bottom: 0,
  },
  subView: {
    width: '100%',
    height: WINDOW_HEIGHT - 150,
    backgroundColor: DARK_GREY,
    borderTopStartRadius: WINDOW_WIDTH * 0.08,
    borderTopEndRadius: WINDOW_WIDTH * 0.08,
    flexDirection: 'column-reverse',
    overflow: 'hidden',
  },
  questionStyle: {
    color: WHITE,
    width: '95%',
    fontSize: 19,
    textAlign: 'center',
    marginTop: 40,
    lineHeight: 40,
  },
  missingWordStyle: {
    color: WHITE,
    width: '100%',
    textAlign: 'center',
    marginTop: 40,
  },
  popMainViewStyle: {flex: 1, alignItems: 'center'},
  popScrollViewStyle: {width: '100%'},
  popSubViewStyle: {flex: 1, alignItems: 'center'},
  textBlankStyle: {
    fontSize: 19,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  txtAnsBlankVIewSTyle: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    bottom: -5,
    borderRadius: 17,
    overflow: 'hidden',
    color: WHITE,
  },
  txtAnsView: {textDecorationLine: 'underline', color: WHITE},
  creditCardMainView: {
    width: WINDOW_WIDTH - 40,
    aspectRatio: 1.55,
    backgroundColor: LIGHT_GREEN,
    borderRadius: 10,
    marginTop: -10,
  },
  creditCardView: {
    aspectRatio: 1.75,
  },
  creditCardImage: {
    height: '100%',
    width: '100%',
    resizeMode: 'contain',
    position: 'absolute',
  },
  creditCardNumberText: {
    color: 'white',
    marginTop: '8%',
    marginLeft: '10%',
    width: '80%',
    fontSize: 20,
    fontWeight: 'bold',
  },
  txtDebit: {
    fontSize: 25,
    color: WHITE,
    fontWeight: 'bold',
    marginTop: -20,
  },
  txtAvailable: {
    fontSize: 13,
    color: WHITE,
    marginTop: 20,
  },
  mainViewAvailableBalance: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  txtAVailableBalance: {
    fontSize: 22,
    color: WHITE,
    fontWeight: 'bold',
    marginLeft: 12,
  },
  cardContainer: {
    width: WINDOW_WIDTH,
    flex: 1,
    backgroundColor: 'white',
    marginTop: 140,
    alignItems: 'center',
    paddingHorizontal: 20,
    borderTopRightRadius: 17,
    borderTopLeftRadius: 17,
  },
  cardNumberView: {
    height: 40,
    width: 160,
    marginTop: -150,
    right: 0,
    backgroundColor: WHITE,
    alignSelf: 'flex-end',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
  },
  cardNumberTouch: {
    flexDirection: 'row',
    marginTop: -10,
  },
  imgViewCardShow: {
    width: 16,
    aspectRatio: 1,
    marginRight: 5,
  },
  imgCardShowHide: {width: '100%', height: '100%', resizeMode: 'contain'},
  txtCardShowHide: {fontSize: 12, fontWeight: '600', color: LIGHT_GREEN},
  spendingLimitMainView: {
    width: '100%',
    marginTop: 20,
    marginBottom: 15
  },
  spendingLimitView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  spendingLimitTitle: {
    fontSize: 13,
    color: GRAY_TEXT,
  },
  remainingLimitText: {
    fontSize: 13,
    color: LIGHT_GREEN,
  },
  limitText: {
    fontSize: 13,
    color: DARK_GREY,
  },
  mainProgreessView: {
    marginTop: 5,
    width: '100%',
    height: 15,
    borderRadius: 10,
    backgroundColor: 'rgb(224, 250, 238)',
  },
  subProgreessView:{
    width: '30%',
    height: '100%',
    position: 'absolute',
    zIndex:1,
    overflow: 'hidden',
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    backgroundColor: LIGHT_GREEN,
  }
});

export default styles;
